### ISSUE TITLE
Setup libcellml buildbot

### ISSUE THREAD

**Issue by codecurve** [cellml/libcellml-archived#11]
Some progress already made:
Ubuntu 12.04 and 14.04 slaves partially done, forced builds working off this branch for now: https://github.com/codecurve/libcellml/tree/buildBotDummy01

**Comment by agarny** [comment]
I appreciate that the ABI may still have Ubuntu 12.04 LTS on some machines, but considering that there is 14.04 LTS, I would just go for this one, as well as for any subsequent version of Ubuntu until the next LTS.

**Comment by nickerso** [comment]
The ABI buildbot is now building and testing libcellml across all supported platforms. See http://autotest.bioeng.auckland.ac.nz/libcellml-buildbot/waterfall for the current status.
