### ISSUE TITLE
Mac OS X buildslaves

### ISSUE THREAD

**Issue by codecurve** [cellml/libcellml-archived#12]
First priority (I think): OS X 10.9, then 10.8 maybe.  I don't think we need 10.7.
Part of issue #11.

**Comment by agarny** [comment]
FWIW:
- The name "Mac OS X" is valid up to version 10.7. From 10.8 onward, it's "OS X".
- OpenCOR supports Mac OS X 10.7.

**Comment by poul-nielsen** [comment]
OS X 10.9 (Mavericks) is currently used on around 65% of Macintosh computers, with 10.8 (Snow Leopard) and 10.7 (Mountain Lion) around 10% each. OS X 10.10 (Yosemite) will probably be released next month with a rapid adoption rate. An OS X 10.9 version of OpenCOR is urgently needed, followed as soon as possible by 10.10. Earlier versions are much less relevant.

**Comment by nickerso** [comment]
I think what Alan meant is that OpenCOR supports 10.7 and beyond with a single build of OpenCOR on a 10.7 machine. OpenCOR certainly works fine out of the box on 10.9.

**Comment by agarny** [comment]
Sorry, OpenCOR does indeed support 10.7 and above. In fact, it is built with the 10.7 SDK, which is supported on later versions of OS X (similarly the 10.9 SDK only works on 10.9 and above). This means that, as soon as 10.10 is out, OpenCOR will support it (and if it doesn't, I will make sure that it does!).

**Comment by nickerso** [comment]
complete and currently working. Will need to see if the range of build machines is suitable as the code starts becoming useful for people to use in their projects or tests.
