### ISSUE TITLE
Windows buildslave(s)

### ISSUE THREAD

**Issue by codecurve** [cellml/libcellml-archived#13]
Windows 7 (64 bit) is all that I think is needed for now.
MSVC (whichever is currently the latest version available on ABI Build and Test Server (BaTS))

**Comment by codecurve** [comment]
Part of #11

**Comment by agarny** [comment]
I would suggest using MSVC 2013, both 32-bit and 64-bit (those are the versions used by OpenCOR on Windows).

**Comment by nickerso** [comment]
Complete and currently working.
