### ISSUE TITLE
Setup buildbot e-mail notification

### ISSUE THREAD

**Issue by codecurve** [cellml/libcellml-archived#14]
Setup mailing list and e-mail notification for failed builds.

**Comment by nickerso** [comment]
Is this still needed given the integration of buildbot with github pull requests for the libcellml project?

**Comment by nickerso** [comment]
apparently no need, so closing.

**Comment by codecurve** [comment]
If it was set up well, it would be nice.  By "set up well", I mean that it only e-mails when the status of a branch's build changes (i.e. on the first fail, then no e-mails until it is fixed, then no e-mail) .  Getting an e-mail for every build is more of a hindrance than an help.
