### ISSUE TITLE
Use of `#pragma once` rather than include guards?

### ISSUE THREAD

**Issue by codecurve** [cellml/libcellml-archived#29]
See https://en.wikipedia.org/wiki/Pragma_once.
Seems like a feature that we should use, supported but the compilers that we care about.

**Comment by nickerso** [comment]
I think the opening sentence of that wikipedia page provides the answer: "In the C and C++ programming languages, #pragma once is a non-standard but widely supported preprocessor directive...". Non-standard seems like a bad thing to me.

Doesn't seem to be anything wrong with header guards so no need to not use them in my view.

**Comment by agarny** [comment]
I was initially going to be in favour of using `#pragma once`, but the fact it's not part of the C/C++ standard is also a no-go for me (e.g., "compilers may use a heuristic that compares file size, modification time and content", so no guarantee whatsoever that `#pragma once` is going to work the same way on different compilers).

**Comment by jonc125** [comment]
Also (from wikipedia, Intel manuals, etc), it appears the pragma isn't necessarily any faster than include guards.

**Comment by codecurve** [comment]
Regarding it being non-standard, see also https://en.wikipedia.org/wiki/Pragma_once#Portability
Regarding speed, I think it saves a very small amount of effort for developers and reviewers, since it is less error prone.
The cases where the pragma may fail seem to be rare.

I'd suggest we give it a go, and if it ever turns out to be a problem, we just revert to include guards.

**Comment by nickerso** [comment]
I think given the majority are against using pragma once the more appropriate way forward is to not use it and if the header guards prove a problem then we can give it a go.

**Comment by codecurve** [comment]
Note that currently include guards are what are being used (although there are only a handful of headers at the moment anyway).  It would be good if those who were put off by the lack of standardisation could clarify whether they considered the info on portability.

From what I can tell, views at the moment are:

In favour of switching to using pragma:
Randall

Against:
Alan
David

Not decided yet:
Jonathan

**Comment by hsorby** [comment]
I am also against the use of  pragma once.  If you cannot manage your header guards then you will have much bigger problems arising.

**Comment by mirams** [comment]
I'd have to say against. Even a lot of expert C/C++ developers won't know about this pragma thing, whereas everybody with any C/C++ knowledge knows about the `#ifndef` way of doing it.

**Comment by nickerso** [comment]
So we will go with header guards for now and revisit this issue if problems arise in the future.
