### ISSUE TITLE
Choice of initial design representation method

### ISSUE THREAD

**Issue by codecurve** [cellml/libcellml-archived#3]
Suggestions so far:
UML
IDL (using a custom back-end to demonstrate C++ equivalent)
Text
C++ Headers and sample client code.

**Comment by codecurve** [comment]
For UML, a tool that understands the underlying model, rather than just treating it as a diagram is my preference, e.g.

Eclipse Papyrus: http://www.eclipse.org/papyrus/ (open source, but doesn't reverse or generate C++, I've used this only for a very brief time before)

MagicDraw: http://www.nomagic.com/products/magicdraw.html and http://en.wikipedia.org/wiki/Magicdraw (commercial, free reader, generates and reverses C++, I've used this extensively before, it's really good in closed source projects, perhaps not ideal for an open source project).

ArgoUML used to be good, but seems to be unmaintained since a few years ago.

**Comment by mtcooling** [comment]
UML-esque (objects, relationships, methods, with object types, attributes (could even skip those, maybe)). Should be able to generate initial C++ from UML in some tool or other. I'm pretty sure I've done that with Rational Rose but not sure what the modern equivalent is.

**Comment by codecurve** [comment]
I've used Rational Rose extensively, but over a decade ago! 
Seems to sort of still be around, e.g. http://www-03.ibm.com/software/products/en/rational-software-architect-family
Back when I used MagicDraw, I found I preferred it to Rose.

**Comment by codecurve** [comment]
Another option, and one that allows us to have the best of all three worlds:
IDL --> Doxygen --> UML
Then, if we want to see C++, we go IDL --> C++

However, you end up with very little control over the UML diagrams :-(

**Comment by codecurve** [comment]
Eclipse Papyrus can generate C++ from UML, haven't tested the limits yet.

**Comment by agarny** [comment]
Personally, I like to be able to visualise things, so my preference would be for UML.

**Comment by nickerso** [comment]
Closing as we have decided to go with a UML-esque view. From Mike's original email definition of "UML-esque":

> And as for discussion format I think UML-esque would be good (not full UML, that'd be a massive overkill. As I said: objects, relationships, attributes, methods).

**Comment by codecurve** [comment]
First views here of presentation of UML here, (model itself is still WIP) :
https://github.com/codecurve/libcellml/blob/uml01/imageExports/libCellML_01_01.PNG

This is for the purposes of feedback on whether we are happy with this way of representing the model, since it demonstrates my understanding of "UML-esque".

**Comment by nickerso** [comment]
Hi Randall, I'd suggest putting this under a new issue rather than posting here under a closed item.

**Comment by codecurve** [comment]
Hi Andre.  I'm not sure what to call the new issue.  I've appended my previous comment to make it clearer why I made that comment.
