### ISSUE TITLE
File name case convention?

### ISSUE THREAD

**Issue by codecurve** [cellml/libcellml-archived#30]
I'm currently using a camel-case convention for C++ source file names, (e.g. would be `VariableSetHelper.h`). Hugh suggested I change the case convention to all lower case (e.g. would be `variablesethelper.h`).

I prefer camel-case. As my example shows, all lower case makes file names look garbled (it's easy to think the first word was "variables" in the lower case example, and "helper" doesn't stand out at the end of the name, since "the"  and "per" might be noticed first). The all lower case convention was strongly influenced historically by quirks when using CVS version control. I've used camel case on a C++ project consistently for 5 years a few years ago, and even using CVS, we felt it was preferable. Chaste uses a camel case convention.

What are other people's views on this?

**Comment by nickerso** [comment]
modern IDEs mean the file name is pretty much irrelevant. Various OS requirements make all lowercase (or uppercase) files more portable and less likely to cause problems. The default file names in QtCreator are all lowercase.

My vote is for all lowercase.

**Comment by hsorby** [comment]
I think this is just a choice you make and once you do, put it in your coding style document.  There are pros and cons for either convention.

My vote is for all lowercase

**Comment by agarny** [comment]
I am also in favour of all lowercase when it comes to file names. It does indeed make things easier for portability.

Otherwise, while we are at it, we might want to 'reopen' issue #16. Yesterday, I came across some code in this repository and I must confess that I didn't like the coding style. Now, I agree that it's all very subjective, but it might nonetheless be worth agreeing on something that looks good to most, is 'efficient', etc.

**Comment by nickerso** [comment]
It seems we should go with lowercase for now and revisit this if it becomes an issue in future.

**Comment by jonc125** [comment]
Just to add, if we're going for all lowercase, I'd suggest separating words by underscores, as is done (e.g.) for Python module names. It avoids the issue with being unable to parse the words that Randall mentioned.

As Randall notes we've never had portability issues with file names in Chaste, but then we're careful not to have names that are identical apart from case.
